import {emojiTree} from './emoji';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { Music2, Pause, X } from 'lucide-react';
import { loveConfig as c } from './data/content';
export function personal(text:string){return text;}
export function Reveal({children,className=''}:{children:ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:.65}}>{children}</motion.div>}
export function Poetry(){return <section className="poetry section" id="poetry"><Reveal><span className="eyebrow">WORDS THAT STAY</span><h2 dir="ltr" lang="en">{emojiTree(c.labels.poetry)}</h2><div className="verses">{c.poetry.map((v,i)=><p lang="en" dir="ltr" key={i}>{v}</p>)}</div><small>Original verses · written for this little space</small></Reveal></section>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{const d=ref.current!;const prior=document.activeElement as HTMLElement|null;d.showModal();closeRef.current?.focus();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d.close();document.body.style.overflow=overflow;prior?.focus();}},[]);return <dialog ref={ref} className="modal" aria-labelledby="dialog-title" onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><button ref={closeRef} onClick={onClose} className="close" aria-label="Close dialog"><X size={22}/></button><h2 id="dialog-title">{emojiTree(title)}</h2>{children}</dialog>}
export function Music(){if(!c.music)return null;return <MusicPlayer/>;}
function MusicPlayer(){const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false);const [error,setError]=useState(false);async function toggle(){if(!audio.current)return;if(playing){audio.current.pause();setPlaying(false);return}try{await audio.current.play();setPlaying(true);setError(false)}catch{setError(true);setPlaying(false)}}return <div className="music-wrap"><audio ref={audio} src={c.music} preload="none" loop onError={()=>{setPlaying(false);setError(true)}}/><button className="music" onClick={toggle} aria-label={playing?'Pause music':'Play music'} aria-pressed={playing}>{playing?<Pause size={18}/>:<Music2 size={18}/>}<span>{playing?'Pause':'Music'}</span></button>{error&&<p role="status" className="music-note">Music is optional. Add your audio to enjoy it here.<button onClick={()=>setError(false)} aria-label="Dismiss music notice">×</button></p>}</div>}
export function Footer(){return <footer>Made with love & code by {c.yourName}<span>♡</span></footer>}
export function HeartBurst({onEnd}:{onEnd:()=>void}){const reduced=useReducedMotion();useEffect(()=>{const t=setTimeout(onEnd,1600);return()=>clearTimeout(t)},[onEnd]);return <div className="heart-burst" aria-hidden="true">{Array.from({length:14},(_,i)=><motion.span key={i} initial={{x:0,y:0,opacity:1,scale:.4}} animate={reduced?{opacity:0}:{x:Math.cos(i*2.4)*140,y:Math.sin(i*2.4)*140-80,opacity:0,scale:1.4}} transition={{duration:1.5}}>♥</motion.span>)}</div>}

export function Nicknames(){return <div className="nickname-ribbon" aria-label="My affectionate names for you">{c.nicknames.map(n=><span key={n}>{n}</span>)}</div>}
export function Birthday(){const [opened,setOpened]=useState(false);const [wish,setWish]=useState(false);const [message,setMessage]=useState(0);const [burst,setBurst]=useState(false);function surprise(){setOpened(true);setMessage(Math.floor(Math.random()*c.birthday.wishes.length));}return emojiTree(<section className="section birthday-section" id="birthday"><Reveal><span className="eyebrow">A LITTLE UNEXPECTED CELEBRATION</span><h2>Wait… one little surprise.</h2><p>{c.birthday.teaser}</p><button className="btn" onClick={surprise} aria-expanded={opened}>{opened?'Another birthday wish 🎂':'A little birthday surprise 🎂'}</button>{opened&&<motion.div className="birthday-card" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><span className="birthday-cake" aria-hidden="true">{wish?'🎂 ✨':'🎂 🕯️'}</span><h3>{c.birthday.heading}</h3><p>{c.birthday.intro}</p><p aria-live="polite">{c.birthday.wishes[message]}</p><div className="burst-control"><button className="btn secondary" onClick={()=>{setWish(true);setBurst(true)}}>{wish?'Wish made — a little joy for you ♡':c.birthday.button}</button>{burst&&<HeartBurst onEnd={()=>setBurst(false)}/>}</div>{wish&&<p role="status">{c.birthday.afterWish}</p>}</motion.div>}</Reveal></section>);}
